ARG HELIUM_GA_RELEASE=2022.05.19.0
ARG BUILD_ARCH=amd64

FROM quay.io/team-helium/miner:miner-"$BUILD_ARCH"_"$HELIUM_GA_RELEASE"_GA

WORKDIR /opt/miner

ENV HELIUM_GA_RELEASE $HELIUM_GA_RELEASE

COPY docker.config /opt/miner/releases/"$HELIUM_GA_RELEASE"/sys.config
COPY *.sh /opt/miner/
COPY ac-sc-sys.config /opt/miner/config/sys.config

CMD echo "$HELIUM_GA_RELEASE" > /etc/lsb_release

ENTRYPOINT ["/opt/miner/start-miner.sh"]
